spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  database: POSTGRESQL
  show-sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG